// <auto-generated />
using EFCoreProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260729085205_addTables")]
    partial class addTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreProject.Models.DepLocation", b =>
                {
                    b.Property<int>("departmentID")
                        .HasColumnType("int");

                    b.Property<string>("departmentLocation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("departmentID", "departmentLocation");

                    b.ToTable("deplocations");
                });

            modelBuilder.Entity("EFCoreProject.Models.Department", b =>
                {
                    b.Property<int>("departmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentID"));

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("employeeID")
                        .HasColumnType("int");

                    b.HasKey("departmentID");

                    b.HasIndex("employeeID")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCoreProject.Models.Dependent", b =>
                {
                    b.Property<int>("dependentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dependentId"));

                    b.Property<string>("dependentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeID")
                        .HasColumnType("int");

                    b.Property<string>("relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dependentId");

                    b.HasIndex("employeeID")
                        .IsUnique();

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("EFCoreProject.Models.Employee", b =>
                {
                    b.Property<int>("employeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeID"));

                    b.Property<int>("departmentID")
                        .HasColumnType("int");

                    b.Property<string>("empName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeAge")
                        .HasColumnType("int");

                    b.Property<double>("employeeSalary")
                        .HasColumnType("float");

                    b.Property<int>("employeesSSN")
                        .HasColumnType("int");

                    b.Property<int>("superviseID")
                        .HasColumnType("int");

                    b.HasKey("employeeID");

                    b.HasIndex("departmentID");

                    b.HasIndex("superviseID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("EFCoreProject.Models.Project", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projectID"));

                    b.Property<string>("projName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("projectID");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EFCoreProject.Models.empProj", b =>
                {
                    b.Property<int>("employeeID")
                        .HasColumnType("int");

                    b.Property<int>("projectID")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("employeeID", "projectID");

                    b.HasIndex("projectID");

                    b.ToTable("empProjs");
                });

            modelBuilder.Entity("EFCoreProject.Models.DepLocation", b =>
                {
                    b.HasOne("EFCoreProject.Models.Department", "depart")
                        .WithMany()
                        .HasForeignKey("departmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depart");
                });

            modelBuilder.Entity("EFCoreProject.Models.Department", b =>
                {
                    b.HasOne("EFCoreProject.Models.Employee", "manager")
                        .WithOne("managedDepart")
                        .HasForeignKey("EFCoreProject.Models.Department", "employeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("EFCoreProject.Models.Dependent", b =>
                {
                    b.HasOne("EFCoreProject.Models.Employee", "employee")
                        .WithOne("dependent")
                        .HasForeignKey("EFCoreProject.Models.Dependent", "employeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("EFCoreProject.Models.Employee", b =>
                {
                    b.HasOne("EFCoreProject.Models.Department", "depart")
                        .WithMany("employees")
                        .HasForeignKey("departmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProject.Models.Employee", "supervisor")
                        .WithMany("supervisee")
                        .HasForeignKey("superviseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depart");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("EFCoreProject.Models.empProj", b =>
                {
                    b.HasOne("EFCoreProject.Models.Employee", "emp")
                        .WithMany("empProjs")
                        .HasForeignKey("employeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProject.Models.Project", "proj")
                        .WithMany("empProjs")
                        .HasForeignKey("projectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("emp");

                    b.Navigation("proj");
                });

            modelBuilder.Entity("EFCoreProject.Models.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("EFCoreProject.Models.Employee", b =>
                {
                    b.Navigation("dependent")
                        .IsRequired();

                    b.Navigation("empProjs");

                    b.Navigation("managedDepart")
                        .IsRequired();

                    b.Navigation("supervisee");
                });

            modelBuilder.Entity("EFCoreProject.Models.Project", b =>
                {
                    b.Navigation("empProjs");
                });
#pragma warning restore 612, 618
        }
    }
}
