// <auto-generated />
using System;
using E_CommerceTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_CommerceTask.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_CommerceTask.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryID"));

                    b.Property<string>("categName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.HasKey("categoryID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderID"));

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("orderID");

                    b.HasIndex("userID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("E_CommerceTask.Models.OrderProduct", b =>
                {
                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("productID", "orderID");

                    b.HasIndex("orderID");

                    b.ToTable("orderProducts");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productID"));

                    b.Property<int>("categoryID")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productID");

                    b.HasIndex("categoryID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Review", b =>
                {
                    b.Property<int>("reviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reviewID"));

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("reviewID");

                    b.HasIndex("orderID")
                        .IsUnique();

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("E_CommerceTask.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("productsOFOrdersorderID")
                        .HasColumnType("int");

                    b.Property<int>("productsOrdersproductID")
                        .HasColumnType("int");

                    b.HasKey("productsOFOrdersorderID", "productsOrdersproductID");

                    b.HasIndex("productsOrdersproductID");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Order", b =>
                {
                    b.HasOne("E_CommerceTask.Models.User", "userOrder")
                        .WithMany("orderLists")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userOrder");
                });

            modelBuilder.Entity("E_CommerceTask.Models.OrderProduct", b =>
                {
                    b.HasOne("E_CommerceTask.Models.Order", "orders")
                        .WithMany("OP")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_CommerceTask.Models.Product", "products")
                        .WithMany("OP")
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orders");

                    b.Navigation("products");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Product", b =>
                {
                    b.HasOne("E_CommerceTask.Models.Category", "categoryOFproduct")
                        .WithMany("productCategories")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryOFproduct");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Review", b =>
                {
                    b.HasOne("E_CommerceTask.Models.Order", "orderReview")
                        .WithOne("orderOFReview")
                        .HasForeignKey("E_CommerceTask.Models.Review", "orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orderReview");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("E_CommerceTask.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("productsOFOrdersorderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_CommerceTask.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("productsOrdersproductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceTask.Models.Category", b =>
                {
                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("E_CommerceTask.Models.Order", b =>
                {
                    b.Navigation("OP");

                    b.Navigation("orderOFReview")
                        .IsRequired();
                });

            modelBuilder.Entity("E_CommerceTask.Models.Product", b =>
                {
                    b.Navigation("OP");
                });

            modelBuilder.Entity("E_CommerceTask.Models.User", b =>
                {
                    b.Navigation("orderLists");
                });
#pragma warning restore 612, 618
        }
    }
}
